### ISSUE TITLE
Release 0.2.1.2

### ISSUE THREAD

**Issue by ununhexium** [sovity/core-edc#8]
# Release

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:

- [x] Decide a release version. The version must be the Eclipse core-edc version `X.Y.Z` appended with the sovity fork version `.W`, eg. `0.2.1.1`.
- [x] Update the `version` in `gradle.properties`
- [x] Update this issue's title to the new version.
- [x] `release-prep` PR with target version-branch `sovity/X.Y.Z`:
    - [x] Update the `CHANGELOG.md`.
        - [x] Add a clean `Unreleased` version.
        - [x] Add the version to the old section.
        - [x] Add the current date to the old version.
        - [x] Check the commit history for commits that might be product-relevant and thus should be added to the changelog. Maybe they were forgotten.
        - [x] Write or review the `Deployment Migration Notes` section, check the commit history for changed / added
          configuration properties.
        - [x] Write or review a release summary.
        - [x] Write or review the compatible versions section.
        - [x] Remove empty sections from the patch notes.
    - [x] Merge the `release-prep` PR.
- [x] Wait for the `sovity/X.Y.Z` branch to be green. You can check the status in GH [actions](https://github.com/sovity/core-edc/actions).
- [x] [Create a release](https://github.com/sovity/core-edc/releases/new)
    - [x] In `Choose the tag`, type your new release version in the format `vX.Y.Z.W` (for instance `v1.2.3.4`) then
      click `+Create new tag vX.Y.Z.W on release`.
    - [x] Re-use the changelog section as release description, and the version as title.
- [x] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [x] Revisit the changed list of tasks and compare it
  with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/edc-extensions/blob/default/.github/ISSUE_TEMPLATE/release.md).
  Propose changes where it makes sense.
- [x] Close this issue.
